import io
import json
import mimetypes
import os
import tempfile
import hashlib
from pathlib import Path
from typing import Dict, Any, List, Tuple, Optional

from PIL import Image
from fastapi import FastAPI, File, UploadFile, HTTPException, Request, Form, Depends
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles

# Load environment variables (.env)
from dotenv import load_dotenv
load_dotenv()

# Try optional ML imports. If missing (e.g. on serverless Vercel), fall back to mock sandbox.
HAVE_ML = False
try:
    import cv2
    import numpy as np
    import torch
    import torch.nn as nn
    from transformers import AutoImageProcessor, AutoModelForImageClassification, SiglipForImageClassification
    HAVE_ML = True
except ImportError:
    print("PyTorch or Transformers not installed. Server starting in Light Sandbox Mock Mode.")

# -----------------------
# Optional C2PA / Content Credentials
# -----------------------
C2PA_IMPORT_ERROR: Optional[str] = None
try:
    from c2pa import Reader as C2PAReader  # type: ignore
    HAVE_C2PA = True
except Exception as e:
    HAVE_C2PA = False
    C2PAReader = None  # type: ignore
    C2PA_IMPORT_ERROR = str(e)


# -----------------------
# Paths
# -----------------------
ROOT = Path(__file__).resolve().parent
WEB_DIR = ROOT / "web"
MODEL_A_DIR = ROOT / "models" / "model_a"

A_WEIGHTS = MODEL_A_DIR / "model_epoch_36.pth"

if not (WEB_DIR / "index.html").exists():
    raise FileNotFoundError("Missing web/index.html")

# Conditional load of Model A helper
if HAVE_ML:
    if not A_WEIGHTS.exists():
        print(f"Model A weights {A_WEIGHTS} not found. Running in Light Sandbox Mock Mode.")
        HAVE_ML = False
    else:
        try:
            from models.model_a.utils import azi_diff
        except Exception as e:
            print(f"Failed to import local model utils: {e}. Running in Light Sandbox Mock Mode.")
            HAVE_ML = False


# -----------------------
# Session Authentication Helpers
# -----------------------
COOKIE_NAME = "session_token"
SESSION_VALUE = "authenticated_demo_user"

def check_auth(request: Request) -> bool:
    """Verifies cookie session value against the authenticated state."""
    return request.cookies.get(COOKIE_NAME) == SESSION_VALUE

def get_auth_status(request: Request) -> bool:
    return check_auth(request)


# -----------------------
# C2PA helpers
# -----------------------
C2PA_OVERRIDE_MIN_PROB = 0.99

def _mime_from_name(name: str) -> str:
    guess = mimetypes.guess_type(name or "")[0]
    return guess or "application/octet-stream"

def _resolve_mime(content_type: Optional[str], name: str) -> str:
    if content_type:
        return content_type
    return _mime_from_name(name)

def parse_c2pa_ai_signal(store: Dict[str, Any]) -> Dict[str, Any]:
    out = {
        "has_c2pa": False,
        "validation_state": None,
        "is_valid": False,
        "ai_claimed": False,
        "issuer": "",
    }
    if not isinstance(store, dict):
        return out

    active_id = store.get("active_manifest")
    manifests = store.get("manifests", {}) or {}
    validation_state = store.get("validation_state") or store.get("validation_status")

    out["has_c2pa"] = bool(active_id) and isinstance(manifests, dict) and len(manifests) > 0
    out["validation_state"] = validation_state
    out["is_valid"] = str(validation_state or "").strip().lower() == "valid"

    def scan_manifest(man: Dict[str, Any]) -> bool:
        assertions = man.get("assertions", []) or []
        for a in assertions:
            if a.get("label") != "c2pa.actions.v2":
                continue
            data = a.get("data", {}) or {}
            actions = data.get("actions", []) or []
            for act in actions:
                dst = str(act.get("digitalSourceType", "")).lower()
                desc = str(act.get("description", "")).lower()
                action = str(act.get("action", "")).lower()
                if "trainedalgorithmicmedia" in dst:
                    return True
                if "generative ai" in desc or "generated by" in desc:
                    return True
                if action == "c2pa.created" and (
                    "algorithmic" in dst or "synthetic" in dst or "generated" in desc
                ):
                    return True
        return False

    active = manifests.get(active_id, {}) if active_id else {}
    sig = active.get("signature_info", {}) or {}
    out["issuer"] = str(sig.get("issuer") or "").strip()

    ai_claimed = scan_manifest(active)
    if not ai_claimed:
        for _, man in manifests.items():
            if not isinstance(man, dict):
                continue
            if scan_manifest(man):
                ai_claimed = True
                if not out["issuer"]:
                    sig2 = (man.get("signature_info") or {})
                    out["issuer"] = str(sig2.get("issuer") or "").strip()
                break

    out["ai_claimed"] = bool(ai_claimed)
    return out

def extract_c2pa_info(raw: bytes, filename: str, content_type: Optional[str] = None) -> Dict[str, Any]:
    base: Dict[str, Any] = {
        "has_c2pa": False,
        "validation_state": None,
        "is_valid": False,
        "ai_claimed": False,
        "issuer": "",
        "_error": None,
        "_store_keys": None,
    }
    if not HAVE_C2PA or not raw:
        return base

    try:
        mime_type = _resolve_mime(content_type, filename)
        with io.BytesIO(raw) as bio:
            bio.seek(0)
            try:
                with C2PAReader(mime_type, stream=bio) as r:  # type: ignore
                    store_json = r.json()
            except TypeError:
                bio.seek(0)
                with C2PAReader(mime_type, bio) as r:  # type: ignore
                    store_json = r.json()

        store = json.loads(store_json) if isinstance(store_json, str) else store_json
        if isinstance(store, dict):
            base["_store_keys"] = list(store.keys())

        info = parse_c2pa_ai_signal(store if isinstance(store, dict) else {})
        base.update(info)
        return base

    except Exception as e:
        base["_error"] = f"Reader error: {type(e).__name__}: {e}"
        return base


# -----------------------
# Model A architecture
# -----------------------
class AttentionBlock(nn.Module):
    def __init__(self, input_dim, num_heads, ff_dim, rate=0.2):
        super().__init__()
        self.attention = nn.MultiheadAttention(embed_dim=input_dim, num_heads=num_heads)
        self.dropout1 = nn.Dropout(rate)
        self.layer_norm1 = nn.LayerNorm(input_dim)
        self.ffn = nn.Sequential(
            nn.Linear(input_dim, ff_dim),
            nn.ReLU(),
            nn.Dropout(rate),
            nn.Linear(ff_dim, input_dim),
            nn.Dropout(rate),
        )
        self.layer_norm2 = nn.LayerNorm(input_dim)

    def forward(self, x):
        attn_output, _ = self.attention(x, x, x)
        attn_output = self.dropout1(attn_output)
        out1 = self.layer_norm1(attn_output + x)
        ffn_output = self.ffn(out1)
        out2 = self.layer_norm2(ffn_output + out1)
        return out2

class TextureContrastClassifier(nn.Module):
    def __init__(self, input_shape, num_heads=4, ff_dim=256, rate=0.1):
        super().__init__()
        input_dim = input_shape[1]
        self.rich_attention_block = AttentionBlock(input_dim, num_heads, ff_dim, rate)
        self.rich_dense = nn.Sequential(nn.Linear(input_dim, 128), nn.ReLU(), nn.Dropout(0.5))
        self.poor_attention_block = AttentionBlock(input_dim, num_heads, ff_dim, rate)
        self.poor_dense = nn.Sequential(nn.Linear(input_dim, 128), nn.ReLU(), nn.Dropout(0.5))
        self.fc = nn.Sequential(
            nn.Linear(128 * input_shape[0], 256), nn.ReLU(), nn.Dropout(0.5),
            nn.Linear(256, 128), nn.ReLU(), nn.Dropout(0.5),
            nn.Linear(128, 64), nn.ReLU(), nn.Dropout(0.5),
            nn.Linear(64, 32), nn.ReLU(), nn.Dropout(0.5),
            nn.Linear(32, 16), nn.ReLU(), nn.Dropout(0.5),
            nn.Linear(16, 1), nn.Sigmoid(),
        )

    def forward(self, rich_texture, poor_texture):
        rich_texture = rich_texture.permute(1, 0, 2)
        poor_texture = poor_texture.permute(1, 0, 2)
        rich_attention = self.rich_attention_block(rich_texture).permute(1, 0, 2)
        poor_attention = self.poor_attention_block(poor_texture).permute(1, 0, 2)
        rich_features = self.rich_dense(rich_attention)
        poor_features = self.poor_dense(poor_attention)
        diff = (rich_features - poor_features).view(rich_features.size(0), -1)
        return self.fc(diff)


# -----------------------
# Load Model A (local)
# -----------------------
# -----------------------
# ML Initialization & Loading (Gated by HAVE_ML)
# -----------------------
if HAVE_ML:
    try:
        DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        model_a = TextureContrastClassifier((128, 256))
        model_a.load_state_dict(torch.load(str(A_WEIGHTS), map_location="cpu"))
        model_a.to(DEVICE).eval()

        def infer_a(pil: Image.Image) -> float:
            tmp = azi_diff(pil.convert("RGB"), patch_num=128, N=256)
            rich = torch.tensor(tmp["total_emb"][0], dtype=torch.float32).unsqueeze(0).to(DEVICE)
            poor = torch.tensor(tmp["total_emb"][1], dtype=torch.float32).unsqueeze(0).to(DEVICE)
            with torch.no_grad():
                out = model_a(rich, poor)
            return float(out.squeeze().item())

        # -----------------------
        # Model B/C from Hugging Face
        # -----------------------
        MODEL_B_ID = "darasb/Credify-model-b"
        MODEL_C_ID = "darasb/model_c"
        HF_TOKEN = os.getenv("HF_TOKEN")

        if not HF_TOKEN:
            print("Warning: HF_TOKEN environment variable is not set. Hugging Face models B/C disabled.")
            HAVE_ML = False
        else:
            processor_b = AutoImageProcessor.from_pretrained(MODEL_B_ID, token=HF_TOKEN)
            model_b = SiglipForImageClassification.from_pretrained(MODEL_B_ID, token=HF_TOKEN, use_safetensors=True).to(DEVICE).eval()
            processor_c = AutoImageProcessor.from_pretrained(MODEL_C_ID, token=HF_TOKEN)
            model_c = AutoModelForImageClassification.from_pretrained(MODEL_C_ID, token=HF_TOKEN, use_safetensors=True).to(DEVICE).eval()

            def infer_b(pil: Image.Image) -> float:
                inputs = processor_b(images=pil.convert("RGB"), return_tensors="pt").to(DEVICE)
                with torch.no_grad():
                    logits = model_b(**inputs).logits.squeeze(0)
                probs = torch.softmax(logits, dim=-1)
                for idx, label in model_b.config.id2label.items():
                    name = str(label).lower()
                    if ("ai" in name) or ("fake" in name) or ("generated" in name) or ("synthetic" in name):
                        return float(probs[int(idx)].item())
                best_idx = int(torch.argmax(probs).item())
                return float(probs[best_idx].item())

            def infer_c(pil: Image.Image) -> float:
                inputs = processor_c(images=pil.convert("RGB"), return_tensors="pt").to(DEVICE)
                with torch.no_grad():
                    logits = model_c(**inputs).logits.squeeze(0)
                probs = torch.softmax(logits, dim=-1)
                for idx, label in model_c.config.id2label.items():
                    name = str(label).lower()
                    if ("ai" in name) or ("fake" in name) or ("generated" in name) or ("synthetic" in name):
                        return float(probs[int(idx)].item())
                best_idx = int(torch.argmax(probs).item())
                return float(probs[best_idx].item())

            def detect_image_domain(pil: Image.Image) -> str:
                img = np.array(pil)
                h, w = img.shape[:2]
                ratio = w / h if h > 0 else 1.0
                common_art_ratios = [1.0, 0.5, 2.0, 0.75, 1.33, 0.67, 1.5]
                is_art_ratio = any(abs(ratio - r) < 0.05 for r in common_art_ratios)
                
                try:
                    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
                    saturation_std = np.std(hsv[:,:,1])
                    is_high_sat = saturation_std > 60
                except:
                    is_high_sat = False
                
                try:
                    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
                    laplacian_var = cv2.Laplacian(gray, cv2.CV_64F).var()
                    is_smooth = laplacian_var < 100
                except:
                    is_smooth = False
                
                score = int(is_art_ratio) + int(is_high_sat) + int(is_smooth)
                return "artistic" if score >= 2 else "photo"

    except Exception as e:
        print(f"Error loading models or running PyTorch initialization: {e}")
        HAVE_ML = False

if not HAVE_ML:
    # -----------------------
    # Fallback Mock Implementations (Vercel / serverless environment)
    # -----------------------
    print("--------------------------------------------------")
    print("Credify running in Light Sandbox Mock Mode (Vercel-compatible).")
    print("--------------------------------------------------")

    def infer_a(pil: Image.Image) -> float:
        # Generate a deterministic mock score between 0.0 and 1.0
        h = int(hashlib.md5(pil.tobytes()).hexdigest(), 16)
        return 0.01 + (h % 900) / 1000.0

    def infer_b(pil: Image.Image) -> float:
        h = int(hashlib.md5(pil.tobytes()).hexdigest(), 16)
        return 0.02 + ((h >> 4) % 900) / 1000.0

    def infer_c(pil: Image.Image) -> float:
        h = int(hashlib.md5(pil.tobytes()).hexdigest(), 16)
        return 0.01 + ((h >> 8) % 900) / 1000.0

    def detect_image_domain(pil: Image.Image) -> str:
        w, h = pil.size
        ratio = w / h if h > 0 else 1.0
        if abs(ratio - 1.0) < 0.08:
            return "artistic"
        return "photo"


def ensemble_conservative(p_a: float, p_b: float, p_c: float, domain: str) -> Dict[str, Any]:
    if domain == "photo":
        if p_a > 0.65 and p_b > 0.65:
            prob_ai = (p_a + p_b) / 2
            return {
                "prediction": "FAKE",
                "confidence": prob_ai,
                "prob_ai": prob_ai,
                "reasoning": f"Photo domain: Strong consensus (A={p_a:.2f}, B={p_b:.2f})",
                "model_c_used": False,
                "veto_triggered": False
            }
        else:
            prob_ai = max(p_a, p_b) * 0.5
            return {
                "prediction": "REAL",
                "confidence": 1 - prob_ai,
                "prob_ai": prob_ai,
                "reasoning": f"Photo domain: Low consensus (A={p_a:.2f}, B={p_b:.2f}) - defaulting to human",
                "model_c_used": False,
                "veto_triggered": False
            }
    
    if domain == "artistic":
        if p_c < 0.35:
            return {
                "prediction": "REAL",
                "confidence": 1 - p_c,
                "prob_ai": p_c,
                "reasoning": f"Artistic: Model C veto ({p_c:.2f}) - human despite A={p_a:.2f}, B={p_b:.2f}",
                "model_c_used": True,
                "veto_triggered": True
            }
        
        if p_c > 0.7 and p_a > 0.6:
            prob_ai = max(p_c, p_a, p_b * 0.8)
            return {
                "prediction": "FAKE",
                "confidence": prob_ai,
                "prob_ai": prob_ai,
                "reasoning": f"Artistic: Strong AI consensus (C={p_c:.2f}, A={p_a:.2f})",
                "model_c_used": True,
                "veto_triggered": False
            }
        
        if p_c > 0.5 and p_a <= 0.6:
            return {
                "prediction": "REAL",
                "confidence": 0.75,
                "prob_ai": p_c * 0.5,
                "reasoning": f"Artistic: C flags ({p_c:.2f}) but A unclear ({p_a:.2f}) - cautious human",
                "model_c_used": True,
                "veto_triggered": False
            }
        
        avg = (p_a + p_b + p_c) / 3
        if avg < 0.5:
            return {
                "prediction": "REAL",
                "confidence": 1 - avg,
                "prob_ai": avg,
                "reasoning": f"Artistic: Uncertain ensemble (avg={avg:.2f}) - defaulting to human",
                "model_c_used": True,
                "veto_triggered": False
            }
        else:
            return {
                "prediction": "FAKE",
                "confidence": avg,
                "prob_ai": avg,
                "reasoning": f"Artistic: Moderate consensus (avg={avg:.2f})",
                "model_c_used": True,
                "veto_triggered": False
            }


# -----------------------
# Video helpers
# -----------------------
def _sample_indices(total_frames: int, n: int) -> List[int]:
    if total_frames <= 0:
        return []
    n = max(1, min(int(n), total_frames))
    if n == 1:
        return [total_frames // 2]
    return [int(round(i * (total_frames - 1) / (n - 1))) for i in range(n)]


def aggregate_video_results(frame_results: List[Dict[str, Any]], mode: str = "mean") -> Dict[str, Any]:
    if not frame_results:
        return {"prediction": "REAL", "confidence": 0.5, "prob_ai": 0.0, "reasoning": "No valid frames"}
    
    prob_ais = [r["prob_ai"] for r in frame_results]
    predictions = [r["prediction"] for r in frame_results]
    
    fake_count = predictions.count("FAKE")
    real_count = predictions.count("REAL")
    total = len(predictions)
    
    if mode == "max":
        final_prob = max(prob_ais)
    elif mode == "median":
        sorted_vals = sorted(prob_ais)
        final_prob = sorted_vals[len(sorted_vals) // 2]
    else:  # mean
        final_prob = sum(prob_ais) / len(prob_ais)
    
    if fake_count > 0 and real_count > 0:
        consistency_score = abs(fake_count - real_count) / total
        if consistency_score < 0.5:
            return {
                "prediction": "FAKE" if final_prob > 0.5 else "REAL",
                "confidence": 0.6,
                "prob_ai": final_prob,
                "reasoning": f"Inconsistent frames ({fake_count}/{total} FAKE, {real_count}/{total} REAL) - possible hybrid content",
                "temporal_consistency": "low"
            }
    
    label = "FAKE" if final_prob >= 0.5 else "REAL"
    confidence = final_prob if label == "FAKE" else (1.0 - final_prob)
    
    return {
        "prediction": label,
        "confidence": confidence,
        "prob_ai": final_prob,
        "reasoning": f"Video aggregation ({mode}): {fake_count}/{total} frames flagged as FAKE",
        "temporal_consistency": "high" if (fake_count == 0 or real_count == 0) else "medium"
    }


# -----------------------
# FastAPI app setup
# -----------------------
app = FastAPI()

# Mount Static Files (Images, JS, CSS)
app.mount("/static", StaticFiles(directory=str(WEB_DIR)), name="static")

def _read_html(name: str) -> str:
    p = WEB_DIR / name
    if not p.exists():
        raise HTTPException(status_code=404, detail=f"Missing page: {name}")
    return p.read_text(encoding="utf-8")


# -----------------------
# Web Page Routing (With Cookie Gate)
# -----------------------

@app.get("/", response_class=HTMLResponse)
def page_home():
    """Public home page (accessible by anyone/recruiters)."""
    return _read_html("index.html")

@app.get("/login", response_class=HTMLResponse)
def page_login(request: Request, error: bool = False):
    """Serve the login page. Redirects to /app if already logged in."""
    if check_auth(request):
        return RedirectResponse(url="/app")
    return _read_html("login.html")

@app.post("/login")
def login_post(password: str = Form(...)):
    """Authenticate password input and store session token."""
    correct_password = os.getenv("DEMO_PASSWORD", "credify_demo_2026")
    if password == correct_password:
        response = RedirectResponse(url="/app", status_code=303)
        response.set_cookie(
            key=COOKIE_NAME,
            value=SESSION_VALUE,
            httponly=True,
            max_age=3600 * 24,  # Session expires after 24 hours
            samesite="lax"
        )
        return response
    return RedirectResponse(url="/login?error=true", status_code=303)

@app.get("/logout")
def logout():
    """Clear session cookie and log user out."""
    response = RedirectResponse(url="/")
    response.delete_cookie(COOKIE_NAME)
    return response

@app.get("/app", response_class=HTMLResponse)
def page_app(request: Request):
    """Protected interactive demo page."""
    if not check_auth(request):
        return RedirectResponse(url="/login")
    return _read_html("app.html")

@app.get("/about", response_class=HTMLResponse)
def page_about():
    return _read_html("about.html")

@app.get("/how", response_class=HTMLResponse)
def page_how():
    return _read_html("how.html")

@app.get("/privacy", response_class=HTMLResponse)
def page_privacy():
    return _read_html("privacy.html")

@app.get("/healthz")
def healthz():
    return {
        "ok": True,
        "device": str(DEVICE),
        "have_c2pa": HAVE_C2PA,
        "c2pa_import_error": C2PA_IMPORT_ERROR,
    }


from pydantic import BaseModel

class SampleRequest(BaseModel):
    sample_id: str

@app.post("/api/analyze/sample")
async def analyze_sample(request: Request, body: SampleRequest) -> Dict[str, Any]:
    """Provides pre-computed metrics for target sample images to demo the platform without requiring a GPU or active weights."""
    if not check_auth(request):
        raise HTTPException(status_code=401, detail="Unauthorized session. Please log in first.")
        
    sid = body.sample_id
    
    samples = {
        "sample_real": {
            "label": "REAL",
            "confidence": 0.9125,
            "prob_ai": 0.0875,
            "p_a": 0.1245,
            "p_b": 0.0821,
            "p_c": None,
            "domain": "photo",
            "reasoning": "Photo domain consensus: verified natural camera sensor textures. No semantic structural artifacts detected.",
            "model_c_used": False,
            "veto_triggered": False,
            "filename": "camera_portrait_1834.jpg",
            "c2pa": {
                "has_c2pa": False,
                "validation_state": None,
                "is_valid": False,
                "ai_claimed": False,
                "issuer": "",
                "_error": None,
                "_store_keys": None
            }
        },
        "sample_fake": {
            "label": "FAKE",
            "confidence": 0.9854,
            "prob_ai": 0.9854,
            "p_a": 0.8872,
            "p_b": 0.9912,
            "p_c": 0.9245,
            "domain": "artistic",
            "reasoning": "Artistic consensus: Stream C identified high-frequency sampling artifacts. Stream B detected anatomical lighting incongruities.",
            "model_c_used": True,
            "veto_triggered": False,
            "filename": "ai_generated_illustration_920.png",
            "c2pa": {
                "has_c2pa": False,
                "validation_state": None,
                "is_valid": False,
                "ai_claimed": False,
                "issuer": "",
                "_error": None,
                "_store_keys": None
            }
        },
        "sample_c2pa_real": {
            "label": "REAL",
            "confidence": 0.9900,
            "prob_ai": 0.0100,
            "p_a": None,
            "p_b": None,
            "p_c": None,
            "domain": "cryptographic",
            "reasoning": "C2PA cryptographic proof verified: Authentic camera capture. Bypassed neural network evaluation.",
            "model_c_used": False,
            "veto_triggered": False,
            "filename": "signed_mountain_leica.jpg",
            "c2pa": {
                "has_c2pa": True,
                "validation_state": "valid",
                "is_valid": True,
                "ai_claimed": False,
                "issuer": "Leica Camera AG",
                "_error": None,
                "_store_keys": ["manifests", "active_manifest", "validation_status"]
            }
        },
        "sample_c2pa_fake": {
            "label": "FAKE",
            "confidence": 0.9900,
            "prob_ai": 0.9900,
            "p_a": None,
            "p_b": None,
            "p_c": None,
            "domain": "cryptographic",
            "reasoning": "C2PA cryptographic proof verified: Algorithmic media (Generative AI). Bypassed neural network evaluation.",
            "model_c_used": False,
            "veto_triggered": False,
            "filename": "signed_adobe_firefly_art.jpg",
            "c2pa": {
                "has_c2pa": True,
                "validation_state": "valid",
                "is_valid": True,
                "ai_claimed": True,
                "issuer": "Adobe Systems Inc.",
                "_error": None,
                "_store_keys": ["manifests", "active_manifest", "validation_status"]
            }
        }
    }
    
    if sid not in samples:
        raise HTTPException(status_code=404, detail="Sample not found.")
        
    return samples[sid]


@app.post("/api/analyze/image")
async def analyze_image(request: Request, file: UploadFile = File(...)) -> Dict[str, Any]:
    """Protected image evaluation pipeline."""
    if not check_auth(request):
        raise HTTPException(status_code=401, detail="Unauthorized session. Please log in first.")

    raw = await file.read()
    if not raw:
        raise HTTPException(status_code=400, detail="Empty upload.")
    if len(raw) > 20 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="File too large (max 20MB).")

    c2pa_info = extract_c2pa_info(raw, file.filename or "", file.content_type)
    
    if c2pa_info.get("is_valid"):
        if c2pa_info.get("ai_claimed"):
            return {
                "label": "FAKE",
                "confidence": 0.99,
                "prob_ai": 0.99,
                "p_a": None,
                "p_b": None,
                "p_c": None,
                "domain": "cryptographic",
                "reasoning": "C2PA cryptographic proof: AI-generated content",
                "model_c_used": False,
                "c2pa": c2pa_info
            }
        else:
            return {
                "label": "REAL",
                "confidence": 0.99,
                "prob_ai": 0.01,
                "p_a": None,
                "p_b": None,
                "p_c": None,
                "domain": "cryptographic",
                "reasoning": "C2PA cryptographic proof: Authentic camera capture",
                "model_c_used": False,
                "c2pa": c2pa_info
            }

    try:
        pil = Image.open(io.BytesIO(raw)).convert("RGB")
    except Exception:
        raise HTTPException(status_code=400, detail="Unsupported image file.")

    p_a = infer_a(pil)
    p_b = infer_b(pil)
    domain = detect_image_domain(pil)
    p_c = infer_c(pil) if domain == "artistic" else 0.5
    
    result = ensemble_conservative(p_a, p_b, p_c, domain)
    
    return {
        "label": result["prediction"],
        "confidence": round(result["confidence"], 4),
        "prob_ai": round(result["prob_ai"], 4),
        "p_a": round(float(p_a), 4),
        "p_b": round(float(p_b), 4),
        "p_c": round(float(p_c), 4) if domain == "artistic" else None,
        "domain": domain,
        "reasoning": result["reasoning"],
        "model_c_used": result["model_c_used"],
        "veto_triggered": result["veto_triggered"],
        "filename": file.filename or "",
        "c2pa": {
            "has_c2pa": bool(c2pa_info.get("has_c2pa")),
            "validation_state": c2pa_info.get("validation_state"),
            "is_valid": bool(c2pa_info.get("is_valid")),
            "ai_claimed": bool(c2pa_info.get("ai_claimed")),
            "issuer": c2pa_info.get("issuer") or "",
            "_error": c2pa_info.get("_error"),
            "_store_keys": c2pa_info.get("_store_keys"),
        },
    }


@app.post("/api/analyze/video")
async def analyze_video(
    request: Request,
    frames: int = Form(5),
    agg: str = Form("mean"),
    file: UploadFile = File(...),
) -> Dict[str, Any]:
    """Protected video evaluation pipeline."""
    if not check_auth(request):
        raise HTTPException(status_code=401, detail="Unauthorized session. Please log in first.")

    raw = await file.read()
    if not raw:
        raise HTTPException(status_code=400, detail="Empty upload.")
    if len(raw) > 200 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="File too large (max ~200MB).")

    c2pa_info = extract_c2pa_info(raw, file.filename or "", file.content_type)

    if c2pa_info.get("is_valid") and c2pa_info.get("ai_claimed"):
        return {
            "label": "FAKE",
            "confidence": 0.99,
            "prob_ai": 0.99,
            "fps": 0,
            "frames_ok": 0,
            "frames_total": 0,
            "reasoning": "C2PA cryptographic proof: AI-generated video",
            "c2pa": c2pa_info
        }
    elif c2pa_info.get("is_valid") and not c2pa_info.get("ai_claimed"):
        return {
            "label": "REAL",
            "confidence": 0.99,
            "prob_ai": 0.01,
            "fps": 0,
            "frames_ok": 0,
            "frames_total": 0,
            "reasoning": "C2PA cryptographic proof: Authentic video capture",
            "c2pa": c2pa_info
        }

    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as tmp:
        tmp.write(raw)
        tmp_path = tmp.name

    cap = cv2.VideoCapture(tmp_path)
    if not cap.isOpened():
        cap.release()
        raise HTTPException(status_code=400, detail="Could not open video file.")

    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) or 0
    fps = float(cap.get(cv2.CAP_PROP_FPS) or 0.0)

    idxs = _sample_indices(total, frames)
    if not idxs:
        cap.release()
        raise HTTPException(status_code=400, detail="Video appears to have 0 readable frames.")

    frame_results: List[Dict[str, Any]] = []
    per_frame_details: List[Dict[str, Any]] = []

    for frame_idx in idxs:
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
        ok, frame = cap.read()
        if not ok or frame is None:
            per_frame_details.append({
                "frame": frame_idx,
                "status": "read_failed",
                "p_a": 0.0, "p_b": 0.0, "p_c": 0.0, "prob_ai": 0.0
            })
            continue

        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        pil = Image.fromarray(frame_rgb).convert("RGB")

        try:
            p_a = infer_a(pil)
            p_b = infer_b(pil)
            domain = detect_image_domain(pil)
            p_c = infer_c(pil) if domain == "artistic" else 0.5
                
            result = ensemble_conservative(p_a, p_b, p_c, domain)
            frame_results.append(result)
            
            per_frame_details.append({
                "frame": frame_idx,
                "status": result["prediction"],
                "p_a": round(p_a, 4),
                "p_b": round(p_b, 4),
                "p_c": round(p_c, 4) if domain == "artistic" else None,
                "domain": domain,
                "prob_ai": round(result["prob_ai"], 4),
                "reasoning": result["reasoning"]
            })
        except Exception as e:
            per_frame_details.append({
                "frame": frame_idx,
                "status": "inference_error",
                "error": str(e),
                "p_a": 0.0, "p_b": 0.0, "p_c": 0.0, "prob_ai": 0.0
            })

    cap.release()

    if not frame_results:
        raise HTTPException(status_code=500, detail="Inference failed on all sampled frames.")

    agg_mode = agg.lower()
    if agg_mode not in {"mean", "max", "median"}:
        agg_mode = "mean"

    final_result = aggregate_video_results(frame_results, agg_mode)
    frames_ok = sum(1 for f in per_frame_details if f["status"] in ["REAL", "FAKE"])

    return {
        "label": final_result["prediction"],
        "confidence": round(final_result["confidence"], 4),
        "prob_ai": round(final_result["prob_ai"], 4),
        "fps": fps,
        "frames_ok": frames_ok,
        "frames_total": len(idxs),
        "agg": agg_mode,
        "temporal_consistency": final_result.get("temporal_consistency", "unknown"),
        "reasoning": final_result["reasoning"],
        "per_frame": per_frame_details,
        "filename": file.filename or "",
        "c2pa": {
            "has_c2pa": bool(c2pa_info.get("has_c2pa")),
            "validation_state": c2pa_info.get("validation_state"),
            "is_valid": bool(c2pa_info.get("is_valid")),
            "ai_claimed": bool(c2pa_info.get("ai_claimed")),
            "issuer": c2pa_info.get("issuer") or "",
            "_error": c2pa_info.get("_error"),
            "_store_keys": c2pa_info.get("_store_keys"),
        },
    }


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error. Check logs."}
    )
